name: Schedule
on:
  schedule:
    - cron: "10 21 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          python-version: "3.10" #install the python needed
          cache: 'pip'
          
      - name: install required packages
        run: pip install -r requirements.txt
        
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data ${{ steps.date.outputs.date }}" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
