name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          python-version: "3.10" #install the python needed
        
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
